name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file PORT
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Add DB_USER to .env
        run: echo "DB_USER=${{ secrets.DB_USER }}" >> .env
      - name: Add DB_PASSWORD to .env
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      - name: Add DB_HOST to .env
        run: echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
      - name: Add DB_PORT to .env
        run: echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
      - name: Add DB_NAME to .env
        run: echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t pegasus09/final_kantin_ta:v1 . 
      - name: Push docker image to the docker hub
        run: docker push pegasus09/final_kantin_ta:v1
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull pegasus09/final_kantin_ta:v1
      - name: Delete old container
        run: docker rm -f final-kantin-ta-v1
      - name: Run docker container
        run: docker run -d -p 4040:4040 --name final-kantin-ta-v1 pegasus09/final_kantin_ta:v1